### PR TITLE
Modernization of secure input using Console

### PR DESCRIPTION
**Pull request by gwynne**
`getpass()` is very, very old, and deprecated everywhere it exists. This PR switches to `readpassphrase()` on macOS, provides a (incomplete but sufficient) re-implementation of `readpassphrase()` based on that of `libbsd` for Linux, and adds an implementation for Windows using the `conio` interface.

### CODE REVIEW

**Review by MrLotU — APPROVED** [review]
Can't say much about the implementation details (esp. on Linux) but LGTM.

Do we need some form of Unit Tests for this?

**Comment by gwynne** [comment]
@MrLotU i thought about adding tests for it, but in the end, it's difficult to say how one would go about testing the functionality - by design, `readpassphrase()` (whether the real one on macOS or my version on Linux) will only work with `/dev/tty`; a unit test would have to hijack it by unhooking the test process' original controlling terminal and replacing it with a PTY (which, among other things, would do fun stuff if you ever tried to use LLDB on the tests). Even with that, there wouldn't be much meaningful value in the few things such a test could check. And for good measure, most of the kinds of things that would go wrong with such an implementation are compile failures or fatal errors, which unit tests don't help with anyway 😕

**Comment by MrLotU** [comment]
Was thinking something along those lines as well. 👍 Thanks

**Comment by tanner0101** [comment]
These changes are now available in [4.2.2](https://github.com/vapor/console-kit/releases/tag/4.2.2)

**Pull request merged**
