### PR TITLE
rename Logging -> LoggingKit

### PR DESCRIPTION
**Pull request by tanner0101**
This change is breaking, but fixes a critical package incompatibility with https://github.com/apple/swift-log

### CODE REVIEW

**Comment by 0xTim** [comment]
Does this warrant a forum post?

**Comment by tanner0101** [comment]
Done: https://forums.swift.org/t/logging-module-name-clash-in-vapor-3/25466

**Comment by t089** [comment]
Whats the suggested workaround for adopters at the moment before this fix lands?

Kind of blocks my builds now:

```
error: multiple products named 'Logging' in: Console, swift-log
error: multiple targets named 'Logging' in: Console, swift-log
```

**Comment by 0xTim** [comment]
@t089 you can pin the IBM logger version in your manifest - see the forum post for details

**Comment by t089** [comment]
@0xTim Yes, thanks :)  just realised that I did not read as far as suggestion 2.

**Pull request closed without merging**
