### PR TITLE
Fix Windows build break in Terminal.

### PR DESCRIPTION
**Pull request by jeffdav**
There are three things that cause Terminal to not build on Windows:

1. `isprint()` returns an `Int32` which requires an explicit comparison. Easy fix: just compare against `0`.
2. `_getch()` returns an `Int32`, but `Unicode.Scalar()` takes a `UInt32`. So we must cast.
3. The entire implementation of `size` was Posix-specific.  Add a Windows implementation.

### CODE REVIEW

**Comment by jeffdav** [comment]
Note: To build on Windows, first one must update `swift-nio` to this revision or later:
https://github.com/apple/swift-nio/commit/8b66b22895115954dca2f1a6c5ab67172b6a6a1c

**Comment by 0xTim** [comment]
@jeffdav Could you enable Windows CI so we can track this properly? See https://github.com/vapor/jwt-kit/blob/main/.github/workflows/test.yml#L35

**Comment by 0xTim** [comment]
Yeah I'm not expecting it to pass but we can at least track the errors across the modules and make sure we don't add regressions in new code. It will be a while until NIO ships a windows compatible version

**Comment by jeffdav** [comment]
@0xTim https://github.com/vapor/console-kit/pull/206
I'm not super familiar with your workflows but it seems straightforward enough.  LMK if this isn't what you meant.

BTW when I run `swift test` with these fixes + the `swift-nio` fixes everything does pass.  I.e. with this locally:
```
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-log.git", from: "1.5.3"),
        .package(url: "https://github.com/apple/swift-nio.git", revision: "8b66b22895115954dca2f1a6c5ab67172b6a6a1c"),
    ],
```

It looks like `swift-nio` does releases pretty frequently, so hopefully won't have to wait too long for it!

**Comment by 0xTim** [comment]
Ah yeah, we're only using NIOConcurrency helpers, not the rest of NIO. Pity we had to pull that in but those fixes should land soon!

**Comment by jeffdav** [comment]
SwiftNIO released 2.76.0 with the fixes in it.  I believe a rerun of the windows-unit workflow will pass now.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Pull request merged**
